// <auto-generated />
using HistoryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace HistoryService.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    partial class HistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HistoryService.Models.QuantityHistoryEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("FirstUnit").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<double>("FirstValue").HasColumnType("float");
                b.Property<string>("OperationType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("ResultUnit").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<double>("ResultValue").HasColumnType("float");
                b.Property<string?>("SecondUnit").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<double?>("SecondValue").HasColumnType("float");
                b.Property<string?>("TargetUnit").HasMaxLength(50).HasColumnType("nvarchar(50)");

                b.HasKey("Id");
                b.HasIndex("Category");
                b.HasIndex("CreatedAt");
                b.ToTable("QuantityHistory");
            });
#pragma warning restore 612, 618
        }
    }
}
